### DISCUSSION TITLE
Before You Post

### DISCUSSION THREAD

**Discussion by ashuntu** [canonical/steam-snap#60] [Game Reports]
The [Game Reports](https://github.com/canonical/steam-snap/discussions/categories/game-reports) discussion category is intended for users of the Steam Snap to report on functionality of games with their specific setup and discuss solutions, *this is **not** a replacement for [issues](https://github.com/canonical/steam-snap/issues)*.

**Before you make a new post**, look for a post with the game you're reporting first, and instead comment on the existing post with your setup information. You may use the [automated script](https://github.com/canonical/steam-snap/wiki/Troubleshooting#submitting-a-steam-report) that will pre-fill some data for you, or use the template below:

```
os_release: 
    name: <Distro name. Output from `cat /etc/os-release`>
    version: <OS Version. Output from `cat /etc/os-release`>
snap_info: 
    steam_revision: <Steam Snap revision. Output from `snap info steam`>
    snapd_revision: <snapd revision. Output from `snap info snapd`>
lspci: 
    <PCI ID>: <Output from `lspci | grep -E VGA|3D controller`>
    ...
glxinfo: 
    gpu:  <GPU brand. Output from `glxinfo -B`>
    gpu_version:  <GPU driver version. Output from `glxinfo -B`>
lscpu:
    model_name: <CPU brand & model. Output from `lscpu`>
xdg_current_desktop: <$XDG_CURRENT_DESKTOP>
desktop_session: <$DESKTOP_SESSION>
```

*Include any additional pertinent logs or system details.*

**Please also include how the game ran and any issues you faced, if it crashed after starting, never started at all, had issues in a certain portion of the game, etc.**
