### DISCUSSION TITLE
Report: Rimworld

### DISCUSSION THREAD

**Discussion by shanefagan** [canonical/steam-snap#71] [Game Reports]
```
os_release: 
    name: "Ubuntu"
    version: "22.10 (Kinetic Kudu)"
snap_info: 
    steam_revision: 70
    snapd_revision: 17576
glxinfo: 
    gpu: AMD Radeon RX 480 Graphics (polaris10, LLVM 14.0.6, DRM 3.49, 6.1.0-060100rc1daily20221021-generic)
    gpu_version: 4.6 (Core Profile) Mesa 22.3.0-devel (git-141703f 2022-10-19 jammy-oibaf-ppa)
lscpu: 
    model_name: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
```
Rimworld crashes sometimes on load, restarting the app works though
