### DISCUSSION TITLE
Report: Vampire Survivors

### DISCUSSION THREAD

**Discussion by ashuntu** [canonical/steam-snap#79] [Game Reports]
```
os_release: 
    name: "Ubuntu"
    version: "22.10 (Kinetic Kudu)"
snap_info: 
    steam_revision: 70
    snapd_revision: 17679
glxinfo: 
    gpu: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
    gpu_version: 4.6 (Core Profile) Mesa 22.3.0-devel (git-141703f 2022-10-19 jammy-oibaf-ppa)
lscpu: 
    model_name: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
```

Vampire Survivors will not open by default; However, as a workaround, run Steam with `snap run steam` then you can [force it to use Proton](https://github.com/canonical/steam-snap/wiki/FAQ#enable-proton-individually), then select "Play with Steam Overlay enabled" when you click Play and it should work.

![image](https://user-images.githubusercontent.com/101582426/199696382-bd5797d4-a232-48f3-bf85-a626b1637528.png)
