### ISSUE TITLE
Ugly mouse cursor

### ISSUE THREAD

**Issue by Nightmayr** [canonical/steam-snap#10]
When the mouse cursor hovers over the Steam window, it no longer uses the system cursor theme and instead uses the default X11 cursor theme. This cursor normally looks worse on HiDPI screens with fractional scaling enabled.
![Screenshot from 2022-05-02 21-43-09](https://user-images.githubusercontent.com/24817147/166325403-e5eb0605-0afb-4da7-8009-173ffedc2033.png)

**Comment by madsrh** [comment]
This might be related to this Snap issue: https://forum.snapcraft.io/t/very-ugly-cursor-for-spotify-and-kde-snaps/17118

**Comment by jhenstridge** [comment]
Not clear this is the actual problem, but the snap's desktop-launch script says:

```
prepend_dir XCURSOR_PATH "$SNAP/data-dir/icons"
```

But in the snapcraft.yaml we mount the icon themes at $SNAP/share/icons:

```yaml
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
```

If the problem is caused by picking fallback mouse cursors that don't include larger sizes, then changing `data-dir` to `share` in the desktop-launch script might help.
