### ISSUE TITLE
Valheim local dedicated server fails to connect playfab

### ISSUE THREAD

**Issue by conromia** [canonical/steam-snap#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

When trying to connect to a Valheim dedicated server locally hosted on the same network, the connection fails with either direct IP or public IP.
Using non snap version of steam works fine.

### Expected Behavior

Connect to server.

### Steps To Reproduce

1. Have a local dedicated Valheim server setup
2. Install steam from the snap store
3. Install Valheim
4. Run Valheim and try to connect to server

### Environment

```yaml
/usr/share/libdrm/amdgpu.ids: No such file or directory
os_release: 
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info: 
    steam_revision:     150
    snapd_revision:     19993
lspci: 
    2f:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c1)
glxinfo: 
    gpu:                NAVI21 (navi21, LLVM 15.0.7, DRM 3.49, 6.2.0-27-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.1.4 - kisak-mesa PPA
lscpu: 
    model_name:         AMD Ryzen 7 5800X 8-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

![Screenshot from 2023-08-22 11-40-28](https://github.com/canonical/steam-snap/assets/8295583/c0ef8270-450d-4f2d-b7c0-98408c1277cb)
![Screenshot from 2023-08-22 11-40-51](https://github.com/canonical/steam-snap/assets/8295583/07be8166-dd02-42e9-ac8e-1ea6c5f43a53)
