### ISSUE TITLE
No audio in steam store, in games works fine

### ISSUE THREAD

**Issue by Astrosus** [canonical/steam-snap#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

Presently I am getting no sound in the steam store or any other part of the app. I have observed no issues with sound while playing any games launched by steam. Also I do not have any audio issues with other applications chrome, firefox, rhythombox, videos, etc. And to answer the obvious question, yes I have make sure the volume is moved to max in the video player.

I used to use pipewire for audio and have scene reverted back to pulseaudio, no change in results.

### Expected Behavior

Expect to hear sound when a video plays

### Steps To Reproduce

Go to Store
Select any game page
Video auto plays, but hear no sound.

### Environment

```yaml
os_release: 
    name:               "Ubuntu"
    version:            "22.04.3 LTS (Jammy Jellyfish)"
snap_info: 
    steam_revision:     154
    snapd_revision:     20092
lspci: 
    28:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (rev c4)
glxinfo: 
    gpu:                NAVI10 (navi10, LLVM 15.0.7, DRM 3.49, 6.2.0-32-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.1.6 - kisak-mesa PPA
lscpu: 
    model_name:         AMD Ryzen 5 3600 6-Core Processor
xdg_current_desktop:    GNOME
desktop_session:        gnome
```

snap connections steam                                                                                                                                
Interface               Plug                          Slot                                Notes
audio-playback          steam:audio-playback          :audio-playback                     -
audio-record            steam:audio-record            :audio-record                       manual
bluez                   steam:bluez                   -                                   -
content[gaming-mesa]    steam:gaming-mesa             gaming-graphics-core22:gaming-mesa  -
content[gtk-3-themes]   steam:gtk-3-themes            gtk-common-themes:gtk-3-themes      -
content[icon-themes]    steam:icon-themes             gtk-common-themes:icon-themes       -
content[sound-themes]   steam:sound-themes            gtk-common-themes:sound-themes      -
desktop                 steam:desktop                 :desktop                            -
desktop-legacy          steam:desktop-legacy          :desktop-legacy                     -
fuse-support            steam:fuse-support            -                                   -
gsettings               steam:gsettings               :gsettings                          -
hardware-observe        steam:hardware-observe        :hardware-observe                   manual
home                    steam:home                    :home                               -
joystick                steam:joystick                :joystick                           -
mount-observe           steam:mount-observe           -                                   -
network                 steam:network                 :network                            -
network-bind            steam:network-bind            :network-bind                       -
network-control         steam:network-control         -                                   -
opengl                  steam:opengl                  :opengl                             -
personal-files          steam:dot-local-share-steam   -                                   -
process-control         steam:process-control         -                                   -
removable-media         steam:removable-media         :removable-media                    -
screen-inhibit-control  steam:screen-inhibit-control  :screen-inhibit-control             -
shared-memory           steam:shmem                   :shared-memory                      -
steam-support           steam:steam-support           :steam-support                      -
system-observe          steam:system-observe          :system-observe                     manual
uinput                  steam:uinput                  :uinput                             -
upower-observe          steam:upower-observe          :upower-observe                     -
wayland                 steam:wayland                 :wayland                            -
x11                     steam:x11                     :x11                                -

pactl info                                                                                                                                            
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 27
Tile Size: 65472
Server Name: pulseaudio
Server Version: 15.99.1
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.usb-Plantronics_Plantronics_Blackwire_5220_Series_454E5479C0E14D3C9C33DF4A6F775713-00.analog-stereo
Default Source: alsa_input.usb-Plantronics_Plantronics_Blackwire_5220_Series_454E5479C0E14D3C9C33DF4A6F775713-00.mono-fallback
```


### gaming-graphics-core22 version

_No response_

### Anything else?


_No response_
