### ISSUE TITLE
Steam icon missing

### ISSUE THREAD

**Issue by Henne1191** [canonical/steam-snap#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [ ] This is a Steam Snap-specific issue

### Current Behavior

The Steam icon is just blank.

### Expected Behavior

It should show the regular steam icon.

### Environment

```yaml
os_release: 
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info: 
    steam_revision:     154
    snapd_revision:     20092
lspci: 
    00:02.0:            Intel Corporation Iris Graphics 540 (rev 0a)
glxinfo: 
    gpu:                Mesa Intel(R) Iris(R) Graphics 540 (SKL GT3)
    gpu_version:        4.6 (Core Profile) Mesa 23.1.6 - kisak-mesa PPA
lscpu: 
    model_name:         Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### Anything else?

It just disappeared a while ago I cannot remember when exactly. I already tried reinstalling the snap, it didn't help.

![Bildschirmfoto vom 2023-09-19 19-37-05](https://github.com/canonical/steam-snap/assets/37246482/c24c761d-6a1a-483b-bbef-93a490469bdd)
