### ISSUE TITLE
NVidia GPU Driver Upgrade: Missing "libGLX_nvidia.so.0" and "libEGL_nvidia.so.0" dependencies

### ISSUE THREAD

**Issue by ErickLandowski** [canonical/steam-snap#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

Every time I upgrade the GPU Drivers ( NVidia RTX 3050 Mobile ) Steam Snap fails to launch basically any game that runs under Proton. It won't even launch the game. Linux native games run fine.

Today the same thing happened after upgrading to "535.104.05". 

It only happens with Steam Snap, and looks like the only way to have it working back again is if i completely **reinstall** Steam Snap and all its games. Unless there is a way to make it work, which i'm not aware of.

I have Steam Flatpak installed and it works with no issues.

### Expected Behavior

The games running on Proton should work after upgrading GPU drivers, without the need to reinstall Steam snap completely.

### Steps To Reproduce

1) Update Nvidia Drivers
2) Reboot laptop/desktop
3) Refresh Steam snap
4) Launch Steam Proton Game (with no success)

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info:
    steam_revision:     165
    snapd_revision:     20092
lspci:
    01:00.0:            NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] (rev a1)
    06:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c5)
glxinfo:
    gpu:                RENOIR (renoir, LLVM 15.0.7, DRM 3.49, 6.2.0-33-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.1.7 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 7 5800H with Radeon Graphics
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### Anything else?

[snap-logs.txt](https://github.com/canonical/steam-snap/files/12731279/snap-logs.txt)
