### ISSUE TITLE
CS2 no sound

### ISSUE THREAD

**Issue by jor1196** [canonical/steam-snap#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [ ] This is a Steam Snap-specific issue

### Current Behavior

Counter Strike 2 has no sound on snap

### Expected Behavior

Counter Strike 2 must have sound, recognize audio outputs

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "22.04.3 LTS (Jammy Jellyfish)"
snap_info:
    steam_revision:     165
    snapd_revision:     20092
lspci:
    29:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 550 640SP / RX 560/560X] (rev ff)
glxinfo:
    gpu:                POLARIS11 (polaris11, LLVM 15.0.7, DRM 3.49, 6.2.0-33-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.1.7 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 5 1600 Six-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```
