### ISSUE TITLE
libfuse needed for appimage based games

### ISSUE THREAD

**Issue by soumyaDghosh** [canonical/steam-snap#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

Appimage based games need `libfuse.so.2` to run. Today I tried to run SuperTux and it gave me that error.

### Expected Behavior

The game should have run properly.

### Steps To Reproduce

1. Go to Steam Store
2. Install SuperTux
3. Click on Play button and see the game not running

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info:
    steam_revision:     165
    snapd_revision:     20092
lspci:
glxinfo:
    gpu:                Mesa Intel(R) UHD Graphics (TGL GT1)
    gpu_version:        4.6 (Core Profile) Mesa 23.1.7 - kisak-mesa PPA
lscpu:
    model_name:         11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu-wayland
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

```
ERROR: ld.so: object '/home/soumyaxubuntu/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
Uploaded AppInterfaceStats to Steam
```
