### ISSUE TITLE
Gamemoderun not working

### ISSUE THREAD

**Issue by ErickLandowski** [canonical/steam-snap#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

When adding the line `gamemoderun %command%` to a game's launch parameters that doesn't seem to make any difference. The game performance is the same with/without it, and `gamemoded -s` shows that it's inactive. I've tested it with Dying Light 2, Cyberpunk 2077.

I've tested with Steam Flatpak and gamemoderun is able to activate when launched this way (tested on Armored Core 6) , so possibly this is something with snap blocking it?

### Expected Behavior

When a game is started with the flag "gamemoderun", gamemoderun should activate.

### Steps To Reproduce

1 - Right click a Steam game and select properties
2 - In the "General" tab, scroll to the bottom and add `gamemoderun %command%`
3 - Launch the game
4 - Open a terminal and see that the command `gamemoderun -s` will appear as inactive

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info:
    steam_revision:     165
    snapd_revision:     20290
lspci:
    01:00.0:            NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] (rev a1)
    06:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c5)
glxinfo:
    gpu:                RENOIR (renoir, LLVM 15.0.7, DRM 3.49, 6.2.0-34-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.2.1 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 7 5800H with Radeon Graphics
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu-wayland
```
