### ISSUE TITLE
Quake 2 remaster crashes on startup

### ISSUE THREAD

**Issue by dtg01100** [canonical/steam-snap#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

Quake 2 remaster crashes on startup with error, the original executable works fine.

### Expected Behavior

Game starts without issue.

### Steps To Reproduce

Click play button, select Quake II, observe crash.

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.10 (Mantic Minotaur)"
snap_info:
    steam_revision:     165
    snapd_revision:     20290
lspci:
    09:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (rev c4)
glxinfo:
    gpu:                NAVI10 (navi10, LLVM 15.0.7, DRM 3.54, 6.5.0-9-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.2.1 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 7 3700X 8-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

![image](https://github.com/canonical/steam-snap/assets/11304019/bdf83888-1eea-4c7a-bee3-8a713441fde1)
[game_log.txt](https://github.com/canonical/steam-snap/files/12908626/game_log.txt)
