### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Manish-kumar-9601** [canonical/steam-snap#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

proton game is not opening , stuck at opening

### Expected Behavior

expected one to two not work  in my ubuntu ,but nothing is working

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.10 (Mantic Minotaur)"
snap_info:
    steam_revision:     165
    snapd_revision:     20290
lspci:
    01:00.0:            NVIDIA Corporation TU117M (rev a1)
    05:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c6)
glxinfo:
    gpu:                NVIDIA GeForce GTX 1650/PCIe/SSE2
    gpu_version:        4.6.0 NVIDIA 535.113.01
lscpu:
    model_name:         AMD Ryzen 5 5600H with Radeon Graphics
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```
