### ISSUE TITLE
Proton games don't run anymore since nvidia/kernel update on Mantic/amd64

### ISSUE THREAD

**Issue by Slarky** [canonical/steam-snap#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

Since applying the following updates today no proton games launch anymore (they were fine yesterday):

```
Install: nvidia-firmware-535-535.129.03:amd64 (535.129.03-0ubuntu0.23.10.1, automatic)
Upgrade: libnvidia-common-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), libnvidia-fbc1-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), libnvidia-gl-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), libnvidia-gl-535:i386 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), libnvidia-extra-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), nvidia-compute-utils-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), nvidia-driver-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), libnvidia-encode-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), nvidia-utils-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), xserver-xorg-video-nvidia-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), linux-modules-nvidia-535-6.5.0-10-generic:amd64 (6.5.0-10.10, 6.5.0-10.10+1), libnvidia-decode-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), nvidia-kernel-common-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), linux-objects-nvidia-535-6.5.0-10-generic:amd64 (6.5.0-10.10, 6.5.0-10.10+1), linux-modules-nvidia-535-generic-hwe-22.04:amd64 (6.5.0-10.10, 6.5.0-10.10+1), libsndfile1:amd64 (1.2.2-1, 1.2.2-1ubuntu0.23.10.1), snapd:amd64 (2.60.4+23.10, 2.60.4+23.10.1), libnvidia-cfg1-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), nvidia-kernel-source-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1), linux-signatures-nvidia-6.5.0-10-generic:amd64 (6.5.0-10.10, 6.5.0-10.10+1), libnvidia-compute-535:amd64 (535.113.01-0ubuntu3, 535.129.03-0ubuntu0.23.10.1)
``` 

The only suspicious log entry seems to be:

```
Nov 03 12:07:01 ubuntu kernel: python3[11541]: segfault at 88 ip 00007fa5c45586c5 sp 00007ffdf5eff7a0 error 4 in libnvidia-glcore.so.535.129.03[7fa5c32f9000+269d000] likely on CPU 3 (core 3, socket 0)
```

Non-proton games work fine.

### Expected Behavior

Proton games that were working before should still with the newer kernel/nvidia driver.

### Steps To Reproduce

1. have a system with an nvidia gfx
2. run apt update/upgrade
3. make sure you're running 6.5.0-10-generic and nvidia-driver-535
4. try to run a known-to-work Proton game

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.10 (Mantic Minotaur)"
snap_info:
    steam_revision:     165
    snapd_revision:     20290
lspci:
    00:02.0:            Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
    01:00.0:            NVIDIA Corporation TU106M [GeForce RTX 2060 Mobile] (rev a1)
glxinfo:
    gpu:                Mesa Intel(R) Xe Graphics (TGL GT2)
    gpu_version:        4.6 (Core Profile) Mesa 23.2.1 - kisak-mesa PPA
lscpu:
    model_name:         11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu-wayland
```

### gaming-graphics-core22 version

kisak-fresh (default)
