### ISSUE TITLE
steam not opening and games are collapsing 

### ISSUE THREAD

**Issue by Manish-kumar-9601** [canonical/steam-snap#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [ ] This is a Steam Snap-specific issue

### Current Behavior

steam not opening and games are collapsing ,my display lagging to opening 

### Expected Behavior

steam not opening and games are collapsing

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.10 (Mantic Minotaur)"
snap_info:
    steam_revision:     165
    snapd_revision:     20290
lspci:
    01:00.0:            NVIDIA Corporation TU117M (rev a1)
    05:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c6)
glxinfo:
    gpu:                RENOIR (renoir, LLVM 15.0.7, DRM 3.54, 6.5.0-10-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.2.1 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 5 5600H with Radeon Graphics
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```
