### ISSUE TITLE
Cannot start X-Plane-12: libatk-bridge-2.0.so.0: undefined symbol: atk_component_scroll_to

### ISSUE THREAD

**Issue by silles79** [canonical/steam-snap#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [ ] This is a Steam Snap-specific issue

### Current Behavior

After selecting language, I'm getting an error:
0:00:16.091 E/SYS: +-------------------------------------------------------------------------------
0:00:16.091 E/SYS: | Loading the required libcef.so failed with error:
0:00:16.091 E/SYS: | /snap/steam/154/usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0: undefined symbol: atk_component_scroll_to
0:00:16.091 E/SYS: | Rerun the X-Plane installer and choose Update to fix your copy of X-Plane.
0:00:16.091 E/SYS: |
0:00:16.091 E/SYS: | (cef_core.cpp:461)
0:00:16.091 E/SYS: +-------------------------------------------------------------------------------

old lib maybe?
ls -l libatk-bridge-2.0.so.0.0.0 
-rw-r--r-- 1 root root 223272 Jan 29  2022 libatk-bridge-2.0.so.0.0.0

### Expected Behavior

Game starts

### Environment

```yaml
os_release: 
    name:               "Ubuntu"
    version:            "23.10 (Mantic Minotaur)"
snap_info: 
    steam_revision:     154
    snapd_revision:     20290
lspci: 
    00:02.0:            Intel Corporation Device 46a6 (rev 0c)
    01:00.0:            NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
glxinfo: 
    gpu:                Mesa Intel(R) Graphics (ADL GT2)
    gpu_version:        4.6 (Core Profile) Mesa 23.2.1 refresh - kisak-mesa PPA
lscpu: 
    model_name:         12th Gen Intel(R) Core(TM) i7-12700H
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu-wayland
```

### gaming-graphics-core22 version

kisak-fresh (default)
