### ISSUE TITLE
Steam can't launch games with Proton compatibility layer due to Vulkan issues

### ISSUE THREAD

**Issue by schranzonator** [canonical/steam-snap#350]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

Proton/Windows games don't start however linux native games are working. When starting steam in the terminal it outputs:
```
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
```
When installing the steam debian package it works flawlessly.

### Expected Behavior

Proton games should start.

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.10 (Mantic Minotaur)"
snap_info:
    steam_revision:     171
    snapd_revision:     20671
lspci:
    01:00.0:            NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)
glxinfo:
    gpu:                NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
    gpu_version:        4.6.0 NVIDIA 535.129.03
lscpu:
    model_name:         Intel(R) Core(TM)2 Quad CPU    Q9650  @ 3.00GHz
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```
