### ISSUE TITLE
Install sticking

### ISSUE THREAD

**Issue by lorimazelee** [canonical/steam-snap#374]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

First quit responding. Second tried beta and caught in a loop at run time container and wouldn't close.

### Expected Behavior

Install and run Steam

### Steps To Reproduce

Click install

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.10 (Mantic Minotaur)"
snap_info:
    steam_revision:     189
    snapd_revision:     21184
lspci:
    00:02.0:            Intel Corporation Device a7ac (rev 04)
glxinfo:
    gpu:                Mesa Intel(R) Graphics (RPL-U)
    gpu_version:        4.6 (Core Profile) Mesa 23.3.4 - kisak-mesa PPA
lscpu:
    model_name:         Intel(R) Core(TM) 5 120U
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

steamwebhelper.sh[89842]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/lori/snap/steam/common/.local/share/Steam/ubuntu12_64/steam-runtime-sniper

steamwebhelper.sh[89842]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/lori/snap/steam/common/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
