### ISSUE TITLE
Snap version of Steam does not keep the credit card information (although the box is ticked)

### ISSUE THREAD

**Issue by vrement** [canonical/steam-snap#375]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

Buying a game from Steam and choosing the payment method of Visa or Mastercard, etc. Does not keep the card information and all has to be filled up again and again in different Steam sessions and purchasing. Works on the .deb version for sure so must be a Steam snap related bug.

### Expected Behavior

To keep the credit card information there, as requested (the box ticked, "remember the card information the next time"). 

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.10 (Mantic Minotaur)"
snap_info:
    steam_revision:     171
    snapd_revision:     21184
lspci:
    00:02.0:            Intel Corporation Device 5906 (rev 02)
glxinfo:
    gpu:                Mesa Intel(R) HD Graphics 610 (KBL GT1)
    gpu_version:        4.6 (Core Profile) Mesa 23.3.4 - kisak-mesa PPA
lscpu:
    model_name:         Intel(R) Pentium(R) CPU 4415U @ 2.30GHz
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### Anything else?

Just tell if additional information is needed. The bug ia quite annoying if buying games often during sales.
