### ISSUE TITLE
 Issue with Steam Snap Version Launching Northgard

### ISSUE THREAD

**Issue by Cardiacman13** [canonical/steam-snap#376]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

I need to force `Steam Linux Runtime 1.0 (scout)` in compatibility option to launch [Northgard](https://www.protondb.com/app/466560)
![image (1)](https://github.com/canonical/steam-snap/assets/83916775/5ae2b1c8-ec04-4556-8cfc-5fbd55243702)

### Expected Behavior

With the .deb version i don't need to force `Steam Linux Runtime 1.0 (scout)` in compatibility option to launch [Northgard](https://www.protondb.com/app/466560)

### Steps To Reproduce

1. Install the snap version of Steam on a Linux system.
2. Attempt to launch Northgard.
3. Observe that the game fails to start.
4. Force `Steam Linux Runtime 1.0 (scout)` in compatibility option
5. Attempt to launch Northgard.
6. Observe that the game start.

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04 LTS (Noble Numbat)"
snap_info:
    steam_revision:     189
    snapd_revision:     21184
lspci:
    01:00.0:            NVIDIA Corporation Device 2757 (rev a1)
glxinfo:
    gpu:                NVIDIA GeForce RTX 4090 Laptop GPU/PCIe/SSE2
    gpu_version:        4.6.0 NVIDIA 550.67
lscpu:
    model_name:         Intel(R) Core(TM) i9-14900HX
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)
