### ISSUE TITLE
Issue with Steam Snap Version Launching Northgard Albion Online

### ISSUE THREAD

**Issue by Cardiacman13** [canonical/steam-snap#377]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

[Albion Online](https://www.protondb.com/app/761890/) fail to start natively (it works with the steam .deb) so i have to force proton experimental. But with proton experimental i have an other issue 
![image (2)](https://github.com/canonical/steam-snap/assets/83916775/4a2bcc8b-9f1e-40f1-9f24-169e759384b3)

The launcher says "not enougth space" but there is enougth, it's work with .deb. 

### Expected Behavior

Albion online start natively without proton and works like with the steam.deb.

### Steps To Reproduce

1 Try to start [Albion Online](https://www.protondb.com/app/761890/)
2 Game crash
3 Force proton experimental in compatibility mode
4 Noticce that the game launcher start but thetre is an eror : "not enougth space" 

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04 LTS (Noble Numbat)"
snap_info:
    steam_revision:     189
    snapd_revision:     21184
lspci:
    01:00.0:            NVIDIA Corporation Device 2757 (rev a1)
glxinfo:
    gpu:                NVIDIA GeForce RTX 4090 Laptop GPU/PCIe/SSE2
    gpu_version:        4.6.0 NVIDIA 550.67
lscpu:
    model_name:         Intel(R) Core(TM) i9-14900HX
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)
