### ISSUE TITLE
Steam will fail if launched via created shortcut (underlying error appears to be Failed to connect to websocket)

### ISSUE THREAD

**Issue by free2create** [canonical/steam-snap#384]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

From a clean/new ubuntu 24.04 install, snap snapshots disabled and no existing snapshots.

If I launch steam via the snap app store :
![image](https://github.com/canonical/steam-snap/assets/266067/1cf60203-016a-40c2-9127-036d720e1e5b)

or the command line as a non privileged user:
![image](https://github.com/canonical/steam-snap/assets/266067/840a8961-0591-4079-8b7a-593127d9821e)

The steam landing page will be displayed:
![image](https://github.com/canonical/steam-snap/assets/266067/2003310c-694e-4e72-bc4c-175309d1108d)

There are errors displayed such as `flock`(LOCK_SH) errors and GLib-GIO-CRITICAL but these don't seem to impact the stability of steam or the one game I have tried.

These logs are in the 

[successful-launch.zip](https://github.com/canonical/steam-snap/files/15439143/successful-launch.zip) attachment

**However**,  if steam is launched using the created shortcut:

![image](https://github.com/canonical/steam-snap/assets/266067/d8b277f5-8a2e-4cc1-987c-fdac28270122)

The quick launcher will be displayed:
![image](https://github.com/canonical/steam-snap/assets/266067/6580e06d-1bbd-4b47-95c3-c554b1c7c978)

However, the Landing page screen fails to be displayed , and if you watch the pinned apps you can observe the landing page icon appearing then disappearing.

In the _console_log.txt_ in the [failed-launch.zip](https://github.com/canonical/steam-snap/files/15439324/failed-launch.zip) the underlying issues appears to be  **Failed to connect to websocket**

### Expected Behavior

When launching steam from the created desktop icon that the landing page (Steam Store) be displayed.

### Steps To Reproduce

1. Click on Show Apps 
![image](https://github.com/canonical/steam-snap/assets/266067/105a792e-6f68-4240-8806-f33b01ba59ba)

2. Click on ![image](https://github.com/canonical/steam-snap/assets/266067/d8b277f5-8a2e-4cc1-987c-fdac28270122)

3. Observe that Steam store windows fails to be displayed.

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04 LTS (Noble Numbat)"
snap_info:
    steam_revision:     191
    snapd_revision:     21759
lspci:
    08:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c4)
glxinfo:
    gpu:                AMD Radeon Graphics (radeonsi, renoir, LLVM 15.0.7, DRM 3.57, 6.8.0-31-generic)
    gpu_version:        4.6 (Core Profile) Mesa 24.0.3 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 9 5900HX with Radeon Graphics
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```
