### ISSUE TITLE
No Mans Sky.  Crash at start up

### ISSUE THREAD

**Issue by kyle142** [canonical/steam-snap#387]
### Ensure there isn't an existing issue for this and check the wiki

- [x] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

The game starts up, get to the main menu and becomes unresponsive then finally crashes to desktop.

### Expected Behavior

No crash. Works on .deb version

### Steps To Reproduce

Install Steam Snap
Run No Mans Sky

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04 LTS (Noble Numbat)"
snap_info:
    steam_revision:     191
    snapd_revision:     21759
lspci:
    08:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Device 744c (rev cc)
glxinfo:
    gpu:                AMD Radeon Graphics (radeonsi, navi31, LLVM 15.0.7, DRM 3.57, 6.8.0-31-generic)
    gpu_version:        4.6 (Core Profile) Mesa 24.0.3 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 7 5800X3D 8-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

Using Proton 9.0-1
Game_log:

```
ERROR: ld.so: object '/home/kyle/snap/steam/common/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kyle/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kyle/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kyle/snap/steam/common/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pressure-vessel-wrap[72575]: W: Failed to load Vulkan ICD #0 from /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json: openat(/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json): No such file or directory
pressure-vessel-wrap[72575]: W: "snap/steam/191/graphics/usr/share/libdrm" is unlikely to appear in "/run/host"
pressure-vessel-wrap[72575]: W: "snap/steam/191/graphics/usr/share/libdrm" is unlikely to appear in "/run/host"
pressure-vessel-wrap[72575]: W: "snap/steam/191/graphics/usr/share/drirc.d" is unlikely to appear in "/run/host"
pressure-vessel-wrap[72575]: W: Not sharing /snap with container to work around https://github.com/canonical/steam-snap/issues/359
pressure-vessel-wrap[72575]: W: Not sharing /var/lib/snapd/hostfs with container to work around https://github.com/canonical/steam-snap/issues/359
pressure-vessel-wrap[72575]: W: Filtering out --tmpfs /snap/steam/191/usr/share/vulkan/implicit_layer.d to work around https://github.com/canonical/steam-snap/issues/370
fsync: up and running.
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
Setting breakpad minidump AppID = 275850
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198016726657 [API loaded no]
/usr/share/libdrm/amdgpu.ids: No such file or directory
Fossilize INFO: Overriding serialization path: "/home/kyle/snap/steam/common/.local/share/Steam/steamapps/shadercache/275850/fozpipelinesv6/steamapprun_pipeline_cache".
pid 72664 != 72660, skipping destruction (fork without exec?)
```
dmesg:

```
[ 2425.697029] audit: type=1400 audit(1717202832.821:1736802): apparmor="DENIED" operation="open" class="file" profile="snap.steam.steam" name="/proc/12939/fdinfo/3" pid=12939 comm="lsof" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[ 2425.697043] audit: type=1400 audit(1717202832.821:1736803): apparmor="DENIED" operation="open" class="file" profile="snap.steam.steam" name="/proc/locks" pid=12939 comm="lsof" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[ 2425.701280] audit: type=1400 audit(1717202832.825:1736804): apparmor="DENIED" operation="ptrace" class="ptrace" profile="snap.steam.steam" pid=12939 comm="lsof" requested_mask="read" denied_mask="read" peer="unconfined"
```

edit:
Added dmesg logs
