### ISSUE TITLE
Launch speed is frustratingly slow due to `/etc/vulkan` violations

### ISSUE THREAD

**Issue by JGCarroll** [canonical/steam-snap#390]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

Running on Ubuntu 24.04 with a RTX 2060 and NVidia drivers 535 with 32bit libraries.

Opening Steam (with no processes running, clean) is frustratingly slow, taking upwards of 1-5 minutes. The apt version launches much quicker.

The snap version  shows error messages relating to being unable to initialize Vulkan, followed by a crashdump generation. The UI eventually appears, after significant delay.

AppArmor shows the following linked denials:
```
Log: apparmor="DENIED" operation="open" class="file" profile="snap.steam.steam" name="/etc/vulkan/explicit_layer.d/" pid=196147 comm="pressure-vessel" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Log: apparmor="DENIED" operation="open" class="file" profile="snap.steam.steam" name="/etc/vulkan/implicit_layer.d/" pid=196147 comm="pressure-vessel" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

### Expected Behavior

The Steam Snap should have access to these directories so that the user experience isn't impacted.

Although I've not tested, I'd also expect this likely breaks games trying to use Vulkan directly (including possibly Proton?).

I've added `/etc/vulkan r,` to the AppArmor profile and reloaded the snap with it. The Vulkan related errors in the console went away, the crashdump doesn't occur, and the login UI appears significantly quicker, on par with the Apt version.

### Steps To Reproduce

1) Open Steam

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04 LTS (Noble Numbat)"
snap_info:
    steam_revision:     191
    snapd_revision:     21759
lspci:
    09:00.0:            NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A] (rev a1)
glxinfo:
    gpu:                NVIDIA GeForce RTX 2060/PCIe/SSE2
    gpu_version:        4.6.0 NVIDIA 535.171.04
lscpu:
    model_name:         AMD Ryzen 7 3700X 8-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

Ultimately this seems like an easy fix of adding `/etc/vulkan r,` to the `steam-support` profile, but I thought I'd raise it here first as there might be nuance I don't understand.
