### ISSUE TITLE
Small steam UI on HiDPI screen

### ISSUE THREAD

**Issue by omar-selo** [canonical/steam-snap#402]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

As you can see from the screenshot below, steam is not respecting my gnome scaling setting (that's 300% on a 4K screen). This is on a fresh install of noble.

![image](https://github.com/user-attachments/assets/fccab5a4-c98e-4817-b7f9-3537a8d844bd)

### Expected Behavior

The steam window and UI should've been 3 times the size it's right now.

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04 LTS (Noble Numbat)"
snap_info:
    steam_revision:     200
    snapd_revision:     21759
lspci:
    0a:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Device 744c (rev cc)
glxinfo:
    gpu:                AMD Radeon Graphics (radeonsi, navi31, LLVM 15.0.7, DRM 3.57, 6.8.0-41-generic)
    gpu_version:        4.6 (Core Profile) Mesa 24.0.3 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 7 2700X Eight-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```
