### ISSUE TITLE
Black Myth: Wukong benchmark has framerate dips that are not present in Steam flatpak

### ISSUE THREAD

**Issue by thatLeaflet** [canonical/steam-snap#403]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

The Steam snap has a lower minimum FPS and has frequent, quick framerate dips. However, I did not notice the drops with my eyes, but this is strange behavior regardless.

This is the benchmark result running on the first release candidate version of Ubuntu 24.04.1, snapd beta 2.65.1 rev 22830, and Steam snap stable rev 200.

![Screenshot from 2024-08-27 19-29-53](https://github.com/user-attachments/assets/1dfca928-386a-4c81-9250-ceec3bbd1929)

### Expected Behavior

I expected behavior to be more similar to the Steam flatpak.

Here is the benchmark result for the Steam flatpak on Fedora Silverblue 40.

![Screenshot from 2024-08-27 18-51-37](https://github.com/user-attachments/assets/5d6ddbee-99db-4d2d-a704-3355f5472cb9)

### Steps To Reproduce

1. Fresh install of Ubuntu 24.04.1
2. Install snapd beta
3. Install Steam
4. Reboot for good measure
5. Run Black Myth Wukong benchmark (free on Steam)

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04.1 LTS (Noble Numbat)"
snap_info:
    steam_revision:     200
    snapd_revision:     22830
lspci:
    2d:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT / 6800M] (rev c1)
glxinfo:
    gpu:                AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 15.0.7, DRM 3.57, 6.8.0-41-generic)
    gpu_version:        4.6 (Core Profile) Mesa 24.0.3 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 5 5600X 6-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

Nothing relevant in dmesg logs.
