### ISSUE TITLE
mangohud parameter not working

### ISSUE THREAD

**Issue by luisalvarado** [canonical/steam-snap#409]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

I read the mangohud documentation at https://github.com/canonical/steam-snap/wiki/FAQ and I am using the Beta and Edge versions. I tested several games from Hogwarts Legacy, to Cyberpunk with the popular:

mangohud %command%

Line but it never showed the mangohud. I also did MANGOHUD=1, mangohud=1, pineapple=1 and other fruits. No luck

### Expected Behavior

Was expecting that if I do this for a game

mangohud %command%

It would show the mangohud.

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04.1 LTS (Noble Numbat)"
snap_info:
    steam_revision:     206
    snapd_revision:     23078
lspci:
    0000:01:00.0:       NVIDIA Corporation Device 2684 (rev a1)
glxinfo:
    gpu:                NVIDIA GeForce RTX 4090/PCIe/SSE2
    gpu_version:        4.6.0 NVIDIA 555.58.02
lscpu:
    model_name:         13th Gen Intel(R) Core(TM) i9-13900K
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```
