### ISSUE TITLE
Ubuntu 24.10 - connected external HDD (games inside): no internet connection / content configuration unavailable on update queue

### ISSUE THREAD

**Issue by dziadulewicz** [canonical/steam-snap#411]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

The internet connection is affirmed to be working correctly (using is also here). A fresh install of Ubuntu 24.10 and a Steam snap from App Center. Seems to work otherwise fine, but as the main storage is changed to external HDD, starts intensive apparently "indexing" type action (as the many games presence is applied). But also as the titles need updates and the list is many, Steam gives: "no internet connection" OR "content configuration unavailable" for the titles. 

The download can be "forced" by keeping clicking "download now" but the connection "drops" right away OR bit later and the title returns to waiting list.. This seems to be a snap package specific (?) because i have experienced this two times now.

The HDD is connected to a laptop via an adapter that makes an older mechanical HDD usable as an external drive (data cable and power).
![steam_bug](https://github.com/user-attachments/assets/80bded0d-6078-4b3c-9f68-b055ec08d95f)
![steam2](https://github.com/user-attachments/assets/ed615078-5385-4887-a565-0455818f778b)
   

### Expected Behavior

The game update downloading to commence as normally in Steam. 

### Steps To Reproduce

Install Ubuntu 24.10. Install Steam Snap. Attach an external HDD drive. Set it as default. Games list appear to library and update queue indicates "no internet connection" OR "content configuration unavailable".

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.10 (Oracular Oriole)"
snap_info:
    steam_revision:     200
    snapd_revision:     21759
lspci:
    00:02.0:            Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
    01:00.0:            NVIDIA Corporation GK107M [GeForce GTX 660M] (rev a1)
glxinfo:
    gpu:                Mesa Intel(R) HD Graphics 4000 (IVB GT2)
    gpu_version:        4.2 (Core Profile) Mesa 24.2.3 - kisak-mesa PPA
lscpu:
    model_name:         Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```
