### ISSUE TITLE
Games under proton universally take 2x as long to load compared to .Deb package 

### ISSUE THREAD

**Issue by anonymousguy31** [canonical/steam-snap#415]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

Loading games under Proton takes a noticeably longer time than when using the .deb steam package. I  tested 3 games in depth (Super Mega Baseball 3, Helldivers 2, and DOOM 2016), and they were oddly all taking 2.33x longer to load to the menu screen near to the second. Longer loading times were present with all my Proton games, however, and with Proton Experimental as well as Proton versions 7.0-9.0. Non-Proton games were unaffected. 

Loading Times: 

smb3 

deb ~45s

snap ~1:45s

doom 

deb ~20s

snap ~45s 

helldivers2

deb ~24s

snap ~56s

### Expected Behavior

Games should load in a comparable length of time to the .Deb package. 

### Steps To Reproduce

1. Install a game using Proton (Experimental, 9.0, 8.0, and 7.0 all produce the same results). 
2. Launch the game
3. The game will take noticeably longer to load to the menu screen than on the .deb package

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.10 (Oracular Oriole)"
snap_info:
    steam_revision:     206
    snapd_revision:     21759
lspci:
    08:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] (rev c1)
glxinfo:
    gpu:                AMD Radeon RX 6600 XT (radeonsi, navi23, LLVM 15.0.7, DRM 3.58, 6.11.0-9-generic)
    gpu_version:        4.6 (Core Profile) Mesa 24.2.3 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 7 5800X 8-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

Attached are the terminal outputs for each game I tested in depth (Super Mega Baseball 3, Helldivers 2, and DOOM 2016). There is a separate text file for each game under the deb package and the snap package. 

[steamlogs.zip](https://github.com/user-attachments/files/17578592/steamlogs.zip)
