### ISSUE TITLE
Default Audio Permissions Cause Certain Games to Hang

### ISSUE THREAD

**Issue by anonymousguy31** [canonical/steam-snap#419]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

Certain Proton games suffer from long load times under default settings using the steam snap. Lack of default permissions granting access to audio recording and bluetooth seems to be the culprit.  

### Expected Behavior

Games should load in a similar time to the .deb package. They do with permissions altered. 

### Steps To Reproduce

1. Install a game using Proton (Experimental, 9.0, 8.0, and 7.0 all produce the same results).
2. Launch the game
3. The game will take noticeably longer to load to the menu screen than on the .deb package 
4. Permit steam access to bluez and audio recording manually (using the "Apps" settings menu)
5. Games now load normally

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.10 (Oracular Oriole)"
snap_info:
    steam_revision:     206
    snapd_revision:     21759
lspci:
    08:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] (rev c1)
glxinfo:
    gpu:                AMD Radeon RX 6600 XT (radeonsi, navi23, LLVM 15.0.7, DRM 3.58, 6.11.0-9-generic)
    gpu_version:        4.6 (Core Profile) Mesa 24.2.3 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 7 5800X 8-Core Processor
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

In reference to the previous issue I opened a few weeks ago (#415), my observation that games seemed to load in after connecting to audio proved to be the culprit for this issue. The error messages I was able to pull consistently were: 

AL lib: (EE) ALCpulseCapture_connectStream: Stream did not get ready: Timeout

and

IPC function call IClientAudio::StartVoiceRecording took too long: 30009 msec

Both of these issues are caused by the application failing to connect  to audio devices, and have been found to cause applications to hang in the past. 

I noticed the steam snap does not have access to either bluez or audio recording by default, and after enabling these connections manually (see screenshot), load times went back down to their expected normals. The two things I remain unclear on is why the package was connecting to these services even without permissions granted, and why this did not seem to impact native Linux games. 

Regardless, it seems like enabling audio recording and bluetooth connections by default might be a good idea. 

![Pasted image](https://github.com/user-attachments/assets/25f67f7d-7ecd-4e0e-bc6c-7c1346a22cf9)
