### ISSUE TITLE
Gyro detection: PS5 Dualsense Controller

### ISSUE THREAD

**Issue by ErickLandowski** [canonical/steam-snap#427]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

Steam when installed via Snap isn't able to detect the gyroscope. It lacks the option to calibrate the gyro, whereas the flatpak version of Steam doesn't present any problem. This is because the snap version of Steam recognizes the controller as "PS5 Controller". In contrast, the flatpak version recognizes as "Dualsense Controller"

### Expected Behavior

The snap version of Steam should correctly detect controller features such as the gyroscope, by recognizing it as a Dualsense controller instead of a "PS5 Controller".

Below are the Steam snap connections (i believe there's nothing missing):

![Steam connections](https://github.com/user-attachments/assets/ab0fa347-5cf8-4445-9699-c5000070c576)

And the comparison of the snap version with the flatpak version. The snap version cannot identify gyroscope and the controller is identified as a PS5 Controller

![Steam snap](https://github.com/user-attachments/assets/1dd62384-2dd3-45e7-abe9-a97a675763de)

![Steam snap PS5 Controller](https://github.com/user-attachments/assets/60c51c42-6fa9-4549-b000-f064aea3e1eb)

The flatpak version of Steam correctly identifies the controller as a Dualsense controller, and for this reason the gyroscope feature is available:

![Steam flatpak](https://github.com/user-attachments/assets/81528af0-fb1b-43a4-876c-9ca4a5330639)

![Steam flatpak dualsense controller](https://github.com/user-attachments/assets/2b33eaeb-a39e-4c15-96de-7936c9852996)

### Steps To Reproduce

1) Have a controller with gyroscope (such as a Playstation Dualsense controller)
2) Open Steam snap
3) Select a game, and to the right-side of the screen click on the controller icon
4) Enable the "Steam Input" feature, and under the "Templates" tab select the "Gamepad with Mouse and Gyro" option
5) See how Gyroscope is unavailable. Also observe the name of the controller under the main menu "Steam > Settings > Controller"
6) Repeat steps 1-5 but at "Step 2" open either Debian or Flatpak versions of Steam instead of the snap version. This time the Gyroscope should be identified and the controller name shall be correct.

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.10 (Oracular Oriole)"
snap_info:
    steam_revision:     206
    snapd_revision:     23258
lspci:
glxinfo:
    gpu:                AMD Radeon Graphics (radeonsi, renoir, LLVM 15.0.7, DRM 3.58, 6.11.0-13-generic)
    gpu_version:        4.6 (Core Profile) Mesa 24.2.3 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 7 5800H with Radeon Graphics
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```
