### ISSUE TITLE
UI flickering on NVIDIA GPU

### ISSUE THREAD

**Issue by YamiYukiSenpai** [canonical/steam-snap#429]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

Steam is flickering on my laptop with NVIDIA GPU.

Doesn't seem to happen when using Radeon

### Expected Behavior

No flickering

### Environment

```yaml
os_release:
    name:               "KDE neon"
    version:            "Unstable Edition"
snap_info:
    steam_revision:     206
    snapd_revision:     23545
lspci:
    01:00.0:            NVIDIA Corporation GP107M [GeForce GTX 1050 3 GB Max-Q] (rev a1)
    05:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c7)
glxinfo:
    gpu:                AMD Radeon Graphics (radeonsi, renoir, LLVM 15.0.7, DRM 3.57, 6.8.0-51-generic)
    gpu_version:        4.6 (Core Profile) Mesa 24.2.3 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 5 4600H with Radeon Graphics
xdg_current_desktop:    KDE
desktop_session:        plasma
```

### Anything else?

[Screencast_20250105_011758.webm](https://github.com/user-attachments/assets/6e335fcd-0b44-4df3-9665-eb8e16a87c42)
