### ISSUE TITLE
Monitor Connection Issues With Nvidia Drivers

### ISSUE THREAD

**Issue by j5awry** [canonical/steam-snap#433]
### Ensure there isn't an existing issue for this and check the wiki

- [x] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

steam: latest/stable :  1.0.0.81 2024-10-24

nvidia: 535 and 550, drivers from Ubuntu archive

GPU: 1660Ti

kernel: 6.8.0-52-generic

ubuntu : 24.04

When launching the steam snap, monitor connections are unstable. Journal fills with gdm-x-session messages

https://paste.ubuntu.com/p/tjwnmxb99T/

with nvidia driver 535, it terminates with a gnome-shell message:

`Failed to connect to colord device xrandr-ViewSonic Corporation-XG270QG-#ASNJN+d71tXd: Failed to connect to missing device /org/freedesktop/ColorManager/devices/xrandr_View>`

this leads to the monitors being disconnected, and the display appearing frozen. disconnecting the monitor cables, and reconnecting them restores the connection. However every 15-30 minutes, the cycle would repeat.

using drive  550, instead of making two attempts to reconnect the monitors, the Nvidia drivers attempt many more times until a stable connection is formed. On first launch from a fresh reboot, this ended up with 26 entries in the journal over 1min15s. The visual symptom was a large amount of video stutter in the desktop environment. All entries are identical to the above paste, but instead of failing, a connection eventually happens. On subsequent launches, I only saw to disconnects, 

I haven't been able to track down anything in the steam logs to help in more debugging. 

### Expected Behavior

* Launching the steam snap does not cause a monitor disconnection

### Steps To Reproduce

1. have an nvidia GPU installed
2. install 535 driver from Ubuntu archive
3. install steam snap
4. sudo journalctl -f 
5. launch steam snap
6. observe monitor display freeze
7. disconnect and reconnect monitors
8. observe disconnect messages in the journal

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "24.04.1 LTS (Noble Numbat)"
snap_info:
    steam_revision:     206
    snapd_revision:     23545
lspci:
    00:02.0:            Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] (rev 02)
    01:00.0:            NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] (rev a1)
glxinfo:
    gpu:                Mesa Intel(R) UHD Graphics 630 (CFL GT2)
    gpu_version:        4.6 (Core Profile) Mesa 24.2.3 - kisak-mesa PPA
lscpu:
    model_name:         Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### gaming-graphics-core22 version

kisak-fresh (default)
