### ISSUE TITLE
Wiki needs updating

### ISSUE THREAD

**Issue by luisalvarado** [canonical/steam-snap#437]
### Ensure there isn't an existing issue for this and check the wiki

- [x] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

Some information is old

### Expected Behavior

The wiki here https://github.com/canonical/steam-snap/wiki/FAQ#enable-proton-globally

Needs the following updates:

- In the section Enable Proton Globally Where it says "Steam > Settings > Steam Play" It should read "Steam > Settings > Compatibility"

- In the same section where it says:
- 
Enabling Steam Play will automatically download Proton compatibility libraries for non-native games. If left disabled, only Native games can be installed and played.

it should read

Enabling Compatibility will automatically download Proton compatibility libraries for non-native games. If left disabled, only Native games can be installed and played.

Basically this continues for the other cases that say "Enable Steam Play" which should be changed to "Enable Compatibility"

The image related to this is also old, this is the new one:

![Image](https://github.com/user-attachments/assets/30913056-8c19-4fd3-95d6-846a8cbd5654)

- For the Controller section, the image needs updating to

### Steps To Reproduce

Same as above

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "25.04 (Plucky Puffin)"
snap_info:
    steam_revision:     206
    snapd_revision:     23545
lspci:
    01:00.0:            NVIDIA Corporation Device 2684 (rev a1)
glxinfo:
    gpu:                NVIDIA GeForce RTX 4090/PCIe/SSE2
    gpu_version:        4.6.0 NVIDIA 570.86.16
lscpu:
    model_name:         13th Gen Intel(R) Core(TM) i9-13900K
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### Anything else?

nothing
