### ISSUE TITLE
Use system Mesa if it's newer than the one in gaming-graphics Snap

### ISSUE THREAD

**Issue by YamiYukiSenpai** [canonical/steam-snap#439]
### Ensure there isn't an existing issue for this and check the wiki

- [x] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

For AMD/Intel GPUs, Steam snap will use the one from gaming-graphics Snap, which hasn't been updated in a while despite the system having newer Mesa.

```
> apt list 'mesa*' --installed
Listing... Done
mesa-libgallium/unknown,now 25.0.0-1~24.04-tux1 amd64 [installed]
mesa-libgallium/unknown,now 25.0.0-1~24.04-tux1 i386 [installed,automatic]
mesa-utils-bin/noble,now 9.0.0-2 amd64 [installed]
mesa-utils/noble,now 9.0.0-2 amd64 [installed]
mesa-va-drivers/unknown,now 25.0.0-1~24.04-tux1 amd64 [installed]
mesa-va-drivers/unknown,now 25.0.0-1~24.04-tux1 i386 [installed]
mesa-vdpau-drivers/unknown,now 25.0.0-1~24.04-tux1 amd64 [installed]
mesa-vdpau-drivers/unknown,now 25.0.0-1~24.04-tux1 i386 [installed]
mesa-vulkan-drivers/unknown,now 25.0.0-1~24.04-tux1 amd64 [installed]
mesa-vulkan-drivers/unknown,now 25.0.0-1~24.04-tux1 i386 [installed,automatic]
```

![Image](https://github.com/user-attachments/assets/04eb9258-df55-4c79-893e-cd9b77e76ea2)

### Expected Behavior

System should use whichever is newer

### Environment

```yaml
os_release:
    name:               "TUXEDO OS"
    version:            "24.04.1 LTS"
snap_info:
    steam_revision:     206
    snapd_revision:     23771
lspci:
    0e:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c0)
    0f:00.0:            NVIDIA Corporation Device 2882 (rev a1)
glxinfo:
    gpu:                AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 15.0.7, DRM 3.59, 6.11.0-109018-tuxedo)
    gpu_version:        4.6 (Core Profile) Mesa 24.2.6 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 9 5900X 12-Core Processor
xdg_current_desktop:    KDE
desktop_session:        plasma
```

### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?

Related: 
https://github.com/canonical/gaming-graphics/issues/29
